
# error

try:
    print("open resource")
    print(10/10)
except Exception:
    print("exception occur")
finally:
    print("close resource")